#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine
# Install nginx web server
# Nginx should be listening on port 80

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html
sudo ngix -t 
sudo service nginx start
