#!/usr/bin/env bash
# installing nginx to the server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw 'Nginx HTTP'

sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'

#testing the configuration
sudo nginx -t

sudo service start
