#!/usr/bin/env bash
# installing nginx to the server

sudo apt-get update
sudo apt-get install nginx
sudo ufw 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

#testing the configuration
sudo nginx -t

sudo service reload
