#!/usr/bin/env bash
#Redirection permanently 301

sudo apt-get update
sudo apt-get install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.html

replacement_file="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/pasej5 permanent;"

sudo sed -i "s/server_name _;/$replacement_file/" /etc/nginx/sites-enabled/default

sudo service nginx restart
