#!/usr/bin/env bash
#custom 404 page that have the string Ceci n'est pas une page

sudo apt-get update
sudo apt-get install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.html

replacement_file="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/pasej5 permanent;"

sudo sed -i "s/server_name _;/$replacement_file/" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
string_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html; {
		\n\troot \/var/www/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$string_replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart
