#!/usr/bin/env bash
# Bash script that configures an Ubuntu server 
# local hosts resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

sudo cp /etc/hosts ~/hosts.backup
sed -i 's/^127.0.0.1*localhost$/127.0.0.2 localhost' ~/hosts.backup
sed -i '/^.*facebook.com.*$/d' ~/hosts.backup
echo "8.8.8.8 facebook.com" >> ~/hosts.backup
sudo cp -f ~hosts.backup /etc/hosts
rm ~/hosts.backup
